global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vchernovolov_alerts'
